language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- npm run deploy
deploy:
- provider: surge
  skip_cleanup: true
  domain: react-polls.surge.sh
  project: ./example/build/
- provider: npm
  email: vini23hot@gmail.com
  api_key:
    secure: xbfiL/FLJEVQHZ86n3LGdoTURcwnDLCLeBBF65CKuqbjc8TIgpDSJrV4diAG7V/r2QNriOUUw3wEdnqJmUUxBQaaNqbp3gUDrTENB0YWUwE/Aa6Kg+AP43UrJWQ3cXGjhHZPDV0PgKPgceFQK/p473SZfRb7bPHlXT5AL6ZU+tr+XQPN9ESWn3mq/oPnUf5C7T3li34alL7KhfYZpVFoAy0g58Nv0N2SoOtmG3GyZN2/O8Llpq0Q9p34GXAZGc+01IKYNuhOml8w4hkEoM3O4RGuoW++8a70nEqsK0+s00u/7SmCvOIVHWTid3f1tMoFj983RFkZ12D0IVRptnHSazCgvX2XNOajYpXlwVt0wLiB87UKIE8QCqKAY8HEsKpygm1OORzeBmAPjEVLh02TrtrRM66vGsIExM3/m1AkFmdHUfXMZpUmPYX+XMNn2v7q1gI0fCzmoMdBZYUnAypLiaHxzTzqZmO9mMZzf+3YT62bRpR4hot8ge+wttpdi6iuCgqxHoU0Xx4Gl2OpyCp2ffK+zbHV2LaWg8SWpUMQl3/DAieZAQM998WsWtAhuE0cqfYzfNyUeykhshEGaOOJKTAQWkFKifFpVyjwn/pMAujD19O7ZJIKZuEXJ3HSxVitFdUz5tzP4BP8x3B91SzMQF4lZ9MnKpRr7YKnr7y3kfk=
  on:
    tags: true
    repo: viniciusmeneses/react-polls

true:
  branch: master
